[tool.poetry]
name = "thesis"
version = "0.1.0"
description = "Package for your thesis"
authors = ["sabijn <sabijn.perdijk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
